### ISSUE TITLE
代理认证跳转地址错误

### ISSUE THREAD

**Issue by chenshaoju** [AstroProfundis/embrr#69]
代码： https://github.com/AstroProfundis/embrr/blob/master/oauth.php#L96 ，这一行可能有问题，其中 '\1/authorize.php\3' 会导致始终跳转到网站根目录去寻找 authorize.php ，如果用户的 embrr 放在二级目录中，则会导致无法通过代理完成验证。

我检查过我的 config.php ，里面的 BASE_URL 无误……

**Comment by shadowglen** [comment]
好吧 这似乎是我的错...
